-- Seed exercises
INSERT INTO exercises (id, name, "bodyPart", "createdAt") VALUES
-- Chest
('ex001', 'ベンチプレス', 'chest', CURRENT_TIMESTAMP),
('ex002', 'インクラインベンチプレス', 'chest', CURRENT_TIMESTAMP),
('ex003', 'デクラインベンチプレス', 'chest', CURRENT_TIMESTAMP),
('ex004', 'ダンベルプレス', 'chest', CURRENT_TIMESTAMP),
('ex005', 'インクラインダンベルプレス', 'chest', CURRENT_TIMESTAMP),
('ex006', 'ダンベルフライ', 'chest', CURRENT_TIMESTAMP),
('ex007', 'ケーブルクロスオーバー', 'chest', CURRENT_TIMESTAMP),
('ex008', '腕立て伏せ', 'chest', CURRENT_TIMESTAMP),
('ex009', 'ディップス（胸）', 'chest', CURRENT_TIMESTAMP),
-- Arms
('ex010', 'バーベルカール', 'arms', CURRENT_TIMESTAMP),
('ex011', 'ダンベルカール', 'arms', CURRENT_TIMESTAMP),
('ex012', 'ハンマーカール', 'arms', CURRENT_TIMESTAMP),
('ex013', 'プリチャーカール', 'arms', CURRENT_TIMESTAMP),
('ex014', 'ケーブルカール', 'arms', CURRENT_TIMESTAMP),
('ex015', 'トライセプスプッシュダウン', 'arms', CURRENT_TIMESTAMP),
('ex016', 'オーバーヘッドトライセプスエクステンション', 'arms', CURRENT_TIMESTAMP),
('ex017', 'スカルクラッシャー', 'arms', CURRENT_TIMESTAMP),
('ex018', 'ディップス（上腕三頭筋）', 'arms', CURRENT_TIMESTAMP),
('ex019', 'ナローグリップベンチプレス', 'arms', CURRENT_TIMESTAMP),
-- Shoulders
('ex020', 'ショルダープレス', 'shoulders', CURRENT_TIMESTAMP),
('ex021', 'ダンベルショルダープレス', 'shoulders', CURRENT_TIMESTAMP),
('ex022', 'サイドレイズ', 'shoulders', CURRENT_TIMESTAMP),
('ex023', 'フロントレイズ', 'shoulders', CURRENT_TIMESTAMP),
('ex024', 'リアデルトフライ', 'shoulders', CURRENT_TIMESTAMP),
('ex025', 'アーノルドプレス', 'shoulders', CURRENT_TIMESTAMP),
('ex026', 'アップライトロウ', 'shoulders', CURRENT_TIMESTAMP),
('ex027', 'シュラッグ', 'shoulders', CURRENT_TIMESTAMP),
-- Back
('ex028', 'デッドリフト', 'back', CURRENT_TIMESTAMP),
('ex029', '懸垂', 'back', CURRENT_TIMESTAMP),
('ex030', 'チンアップ', 'back', CURRENT_TIMESTAMP),
('ex031', 'ベントオーバーロウ', 'back', CURRENT_TIMESTAMP),
('ex032', 'Tバーロウ', 'back', CURRENT_TIMESTAMP),
('ex033', 'シーテッドケーブルロウ', 'back', CURRENT_TIMESTAMP),
('ex034', 'ワンアームダンベルロウ', 'back', CURRENT_TIMESTAMP),
('ex035', 'ラットプルダウン', 'back', CURRENT_TIMESTAMP),
('ex036', 'フェイスプル', 'back', CURRENT_TIMESTAMP),
-- Legs
('ex037', 'スクワット', 'legs', CURRENT_TIMESTAMP),
('ex038', 'フロントスクワット', 'legs', CURRENT_TIMESTAMP),
('ex039', 'ルーマニアンデッドリフト', 'legs', CURRENT_TIMESTAMP),
('ex040', 'レッグプレス', 'legs', CURRENT_TIMESTAMP),
('ex041', 'レッグエクステンション', 'legs', CURRENT_TIMESTAMP),
('ex042', 'レッグカール', 'legs', CURRENT_TIMESTAMP),
('ex043', 'ランジ', 'legs', CURRENT_TIMESTAMP),
('ex044', 'ブルガリアンスクワット', 'legs', CURRENT_TIMESTAMP),
('ex045', 'カーフレイズ', 'legs', CURRENT_TIMESTAMP),
('ex046', 'ヒップスラスト', 'legs', CURRENT_TIMESTAMP),
-- Abs
('ex047', 'プランク', 'abs', CURRENT_TIMESTAMP),
('ex048', 'クランチ', 'abs', CURRENT_TIMESTAMP),
('ex049', 'レッグレイズ', 'abs', CURRENT_TIMESTAMP),
('ex050', 'ロシアンツイスト', 'abs', CURRENT_TIMESTAMP),
('ex051', 'ケーブルクランチ', 'abs', CURRENT_TIMESTAMP),
('ex052', 'アブローラー', 'abs', CURRENT_TIMESTAMP),
('ex053', 'ハンギングニーレイズ', 'abs', CURRENT_TIMESTAMP),
('ex054', 'サイドプランク', 'abs', CURRENT_TIMESTAMP);
